<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Inizios-MacBook-Pro-2.local" failures="1" tests="3" name="Test" time="25.549" errors="0" timestamp="2021-02-11T09:50:35 PST">
  <testcase classname="homePageTestCases.VerifySignInErrorMessage" name="signinError" time="3.295"/>
  <testcase classname="homePageTestCases.VerifySignInErrorMessage" name="signinError1" time="3.477">
    <failure type="java.lang.AssertionError" message="There was a problem expected:&amp;lt;There &amp;gt; but was:&amp;lt;error message is not expected&amp;gt;">
      <![CDATA[java.lang.AssertionError: There was a problem expected:<There > but was:<error message is not expected>
at homePageTestCases.VerifySignInErrorMessage.signinError1(VerifySignInErrorMessage.java:36)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- signinError1 -->
  <testcase classname="homePageTestCases.HomePageHeaderTestCase" name="verifyHeader" time="0.398"/>
</testsuite> <!-- Test -->
